sudo: false

language: ruby
cache: bundler
rvm:
  - 2.3.3

dist: trusty

script:
  - bundle exec jekyll build
  - python tests.py

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  email: false
  webhooks:
    - http://helit.org:8093/+sujevo-dev/showSuccessfulBuildMessages=always
